### ISSUE TITLE
Kod inceleme

### ISSUE THREAD

**Issue by tarkanbattal1071** [beren04/MineSweeper#1]
Merhaba Mine hanım, kodunuzu debug etmeye çalıştığımda birkaç soru oluştu aklımda. Neden map()imizde ilk başta bomba için değerler-1 iken daha sonra -2 yazıyor? Saygılarımla iyi günler.

![Screenshot from 2023-02-21 11-40-57](https://user-images.githubusercontent.com/125374171/220335587-80da83bf-7f65-44f6-a1b7-6b36e9c59606.png)

**Comment by beren04** [comment]
Merhaba,
-2 yazmasının sebebi etrafında mayın olmadığını belirtiyor eğer yanında
mayın varsa zaten mayın sayısı kadar kutucukta o sayı yazıyor. Başka
sorunuz olursa tekrar sorabilirsiniz.

İyi Günler,
Beren E.

tarkanbattal1071 ***@***.***>, 21 Şub 2023 Sal, 14:35
tarihinde şunu yazdı:

**Comment by tarkanbattal1071** [comment]
Öncelikle cevapladığınız için çok teşekkür ederim, yani aslında hocanın 0 olarak yazdığı sizin kodunuzda -2 oluyor sanırım, hocanın - olarak belirttiği baştaki map sizin kodunuzda ise 0 oluyor. Affınıza sığınarak birkaç şey daha eklemek istiyorum, lütfen yanlış anlamayın hata aramak için değil,  kendim anlamak için debug ederken fark ettim. Mesela aşağıdaki görsel için 0 0 girdiğimde 1 yazması gerekirken 2 yazıyor sanırım bir kayma var. 0 1 yazdığımda kaybettiğimi yazıyor, Tekrar çok teşekkür ederim.Saygılarımla , iyi günler
![Screenshot-from-2023-02-21-12-07-52](https://user-images.githubusercontent.com/125374171/220343039-760177ab-883f-45e3-9738-8146a934c0d8.jpeg)

![Screenshot-from-2023-02-21-12-09-00](https://user-images.githubusercontent.com/125374171/220343769-b11d8df9-fba9-4bbd-a477-2d418827c190.jpeg)

**Comment by beren04** [comment]
Yok yok hiç sıkıntı değil ben çok teşekkür ederim çünkü hiç fark
etmemiştim. Tekrar inceleyip kodu düzelteceğim. Dikkatiniz için tekrardan
teşekkürler.
